# Generated by Django 5.2 on 2025-04-09 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('sensor_type', models.CharField(choices=[('temperature', 'Température'), ('humidity', 'Humidité'), ('pressure', 'Pression'), ('volume', 'Volume'), ('energy', 'Energie'), ('status', 'Statut'), ('other', 'Others')], max_length=20)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('condition_operator', models.CharField(choices=[('gt', 'Supérieur à'), ('lt', 'Inférieur à'), ('eq', 'Egal à'), ('neq', 'Différent de'), ('gte', 'Supérieur ou égal à'), ('lte', 'Inférieur ou égal à')], max_length=3)),
                ('condition_value', models.FloatField()),
                ('action_type', models.CharField(choices=[('notification', 'Envoyer notification'), ('email', 'Envoyer email'), ('api_call', 'Appel API externe'), ('custom', 'Action personnalisée')], max_length=20)),
                ('actions_details', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='sensors.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='sensors.sensor')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
