# Generated by Django 5.2 on 2025-04-10 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenario',
            old_name='actions_details',
            new_name='action_details',
        ),
    ]
